spring.application.name=novapos-backend

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/posnova?sslmode=disable&TimeZone=America/Bogota&currentSchema=public
spring.datasource.username=postgres
spring.datasource.password=Gerente
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=America/Bogota

spring.mvc.format.date-time=iso
server.tomcat.uri-encoding=UTF-8

jwt.secret=cGFuYWRlcmlhZHVsY2V2aWRhc2VjcmV0a2V5cG9zbm92YWdlc25ub3ZhMjAyNQ==
jwt.expiration=86400000

aliado.api.url=https://api.aliado.com
aliado.api.token=token_de_prueba
aliado.api.codigo=codigo_de_prueba

multitenancy.default-schema=public